# Coffee Quality Database from CQI (2nd Dataset)

## Imports/Pathways

In [1]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [2]:
# File Pathway
path = r"C:\Users\Chase\anaconda_projects\Exercise_6_Coffee\A6_Coffee"

In [3]:
# Import 2nd dataset
df_cqi = pd.read_csv(
    r'C:\Users\Chase\anaconda_projects\Exercise_6_Coffee\A6_Coffee\02_Data\Original_Data\Coffee_Quality_database_from_CQI\Coffee_Quality_database_from_CQI_mc.csv')

## Data Inspection¶
### Table of Contents
1. Overview
2. Missing Values
3. Duplicate Check
4. Text Field Consistency Audit
5. Column Status: Keep, Drop, or Review

### 1. Overview

In [4]:
# General check of first 10 rows
df_cqi.head()

,Unnamed_Index',Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,ICO.Number.1,...,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,0,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
1,1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,1,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
2,2,Arabica,grounds for health admin,Guatemala,"san marcos barrancas ""san cristobal cuch",NaN,NaN,NaN,NaN,1600 - 1800 m,...,NaN,0,"May 31st, 2011",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,1600.0,1800.0,1700.0
3,3,Arabica,yidnekachew dabessa,Ethiopia,yidnekachew dabessa coffee plantation,NaN,wolensu,NaN,yidnekachew debessa coffee plantation,1800-2200,...,Green,2,"March 25th, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1800.0,2200.0,2000.0
4,4,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,2,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0

In [5]:
# Cehck the dataset shape
df_cqi.shape

(1339, 44)

In [7]:
# List all column headers
df_cqi.columns.tolist()

["Unnamed_Index'",
 'Species',
 'Owner',
 'Country.of.Origin',
 'Farm.Name',
 'Lot.Number',
 'Mill',
 'ICO.Number',
 'Company',
 'ICO.Number.1',
 'Region',
 'Producer',
 'Number.of.Bags',
 'Bag.Weight',
 'In.Country.Partner',
 'Harvest.Year',
 'Grading.Date',
 'Owner.1',
 'Variety',
 'Processing.Method',
 'Aroma',
 'Flavor',
 'Aftertaste',
 'Acidity',
 'Body',
 'Balance',
 'Uniformity',
 'Clean.Cup',
 'Sweetness',
 'Cupper.Points',
 'Total.Cup.Points',
 'Moisture',
 'Category.One.Defects',
 'Quakers',
 'Color',
 'Category.Two.Defects',
 'Expiration',
 'Certification.Body',
 'Certification.Address',
 'Certification.Contact',
 'unit_of_measurement',
 'altitude_low_meters',
 'altitude_high_meters',
 'altitude_mean_meters']

Headers will need work. Proper headers and standardize the text

In [8]:
# Check data types
df_cqi.dtypes

Unnamed_Index'             int64
Species                   object
Owner                     object
Country.of.Origin         object
Farm.Name                 object
Lot.Number                object
Mill                      object
ICO.Number                object
Company                   object
ICO.Number.1              object
Region                    object
Producer                  object
Number.of.Bags             int64
Bag.Weight                object
In.Country.Partner        object
Harvest.Year              object
Grading.Date              object
Owner.1                   object
Variety                   object
Processing.Method         object
Aroma                    float64
Flavor                   float64
Aftertaste               float64
Acidity                  float64
Body                     float64
Balance                  float64
Uniformity               float64
Clean.Cup                float64
Sweetness                float64
Cupper.Points            float64
Total.Cup.Points         float64
Moisture                 float64
Category.One.Defects       int64
Quakers                  float64
Color                     object
Category.Two.Defects       int64
Expiration                object
Certification.Body        object
Certification.Address     object
Certification.Contact     object
unit_of_measurement       object
altitude_low_meters      float64
altitude_high_meters     float64
altitude_mean_meters     float64
dtype: object

### 2. Missing Values

In [9]:
# Create a summary table of missing values for CQI dataset, excluding 0s
missing_count = df_cqi.isnull().sum()
missing_percent = (df_cqi.isnull().mean() * 100).round(2)

missing_summary = pd.DataFrame({
    'Missing Count': missing_count,
    'Missing %': missing_percent
})

# Filter out rows with 0 missing values
missing_summary = missing_summary[missing_summary['Missing Count'] > 0]

# Sorted by highest missing %
missing_summary = missing_summary.sort_values(by='Missing %', ascending=False)

# Display the summary
missing_summary

                      Missing Count  Missing %
Lot.Number                     1063      79.39
Farm.Name                       359      26.81
Mill                            318      23.75
Color                           270      20.16
Producer                        232      17.33
altitude_high_meters            230      17.18
altitude_low_meters             230      17.18
altitude_mean_meters            230      17.18
ICO.Number.1                    226      16.88
Variety                         226      16.88
Company                         209      15.61
Processing.Method               170      12.70
ICO.Number                      159      11.87
Region                           59       4.41
Harvest.Year                     47       3.51
Owner.1                           7       0.52
Owner                             7       0.52
Country.of.Origin                 1       0.07
Quakers                           1       0.07

Looking at this I will be dropping the Lot.Number column, too high % missing to be useful. The rest will be inspected for what can be done.

### 3. Duplicate Check

In [10]:
# Check for duplicate rows
df_cqi.duplicated().sum()

np.int64(0)

No duplicated rows found.

### 4. Text Field Consistency Audit

#### Headers

In [11]:
# Headers are inconsistent 
df_cqi.columns.tolist()

["Unnamed_Index'",
 'Species',
 'Owner',
 'Country.of.Origin',
 'Farm.Name',
 'Lot.Number',
 'Mill',
 'ICO.Number',
 'Company',
 'ICO.Number.1',
 'Region',
 'Producer',
 'Number.of.Bags',
 'Bag.Weight',
 'In.Country.Partner',
 'Harvest.Year',
 'Grading.Date',
 'Owner.1',
 'Variety',
 'Processing.Method',
 'Aroma',
 'Flavor',
 'Aftertaste',
 'Acidity',
 'Body',
 'Balance',
 'Uniformity',
 'Clean.Cup',
 'Sweetness',
 'Cupper.Points',
 'Total.Cup.Points',
 'Moisture',
 'Category.One.Defects',
 'Quakers',
 'Color',
 'Category.Two.Defects',
 'Expiration',
 'Certification.Body',
 'Certification.Address',
 'Certification.Contact',
 'unit_of_measurement',
 'altitude_low_meters',
 'altitude_high_meters',
 'altitude_mean_meters']

Headers will need to be lowercase and have an underscore between the words.Spelling check too.

#### Casing and Spacing Consistency

In [12]:
# Inspect all object-type columns for unique values
for col in df_cqi.select_dtypes(include='object').columns:
    print(f"\n{col} unique values:")
    print(df_cqi[col].dropna().unique())

Species unique values:
['Arabica' 'Robusta']

Owner unique values:
['metad plc' 'grounds for health admin' 'yidnekachew dabessa' 'ji-ae ahn'
 'hugo valdivia' 'ethiopia commodity exchange' 'diamond enterprise plc'
 'mohammed lalo' 'cqi q coffee sample representative'
 'yunnan coffee exchange' 'essencecoffee' 'the coffee source inc.'
 'roberto licona franco' 'nucoffee' 'kabum trading company'
 'bismarck castro' 'lin, che-hao krude 林哲豪' 'nora zeas'
 'specialty coffee-korea' 'francisco a mena' 'hider abamecha'
 'daniel magu' 'kona pacific farmers cooperative' 'itdp international'
 'jacques pereira carneiro' 'jungle estate' 'great lakes coffee uganda'
 'lusso lab' 'afca' 'juan luis alvarado romero' 'kawacom uganda ltd'
 'exportadora de cafe condor s.a' 'gonzalo hernandez'
 'ibrahim hussien speciality coffee producer &export'
 'seid damtew coffee planataion' 'dane loraas' 'colbran coffeelands, ltd.'
 'atlantic specialty coffee' 'assefa belay coffee producer'
 'kyagalanyi ltd' 'rashid moledina & co. (msa) ltd.' 'ibero kenya limited'
 'compañia colombiana agroindustrial s.a' 'nomura trading co., ltd.'
 'carcafe ltda ci' 'steven kil' 'eileen koyanagi' 'kyagalanyi coffee ltd'
 'racafe & cia s.c.a' 'troy quimby' 'el equimite, cafetal biodinámico'
 'simon mahinda' 'young kim' 'carl walker' 'taylor winch (t) ltd'
 'artemio zapata tejeda' 'brian speckman' 'philip schluter'
 '松澤宏樹 koju matsuzawa' 'lydiah mwangi' 'cadexsa'
 'consejo salvadoreño del café' 'sanjava coffee' 'rodrigo soto'
 'fabian calderon mora' 'eric thormaehlen' 'rob tuttle'
 'cqi taiwan icp cqi台灣合作夥伴' 'dream together'
 'organizaciones de productores de cafe colimense' 'benjamin schmerler'
 'taylor winch (coffee) ltd.' 'max gurdian' 'ecom japan limited'
 'federacion nacional de cafeteros' 'eric wu'
 'maria imelda uscanga martinez' 'alfredo bojalil' 'daniel friedlander'
 'alexandra katona-carroll' 'aulia arif syahri' 'kao ming lee'
 'maria amalia guadalupe toriello elorza' 'raúl vargas'
 'victor hugo melchor cordova' 'tembo coffee company ltd'
 'jesus salazar velasco' 'manuel herrera juarez' 'wayner jimenez'
 'cooperativa el gorrion r.l' 'cafebras' 'ceca, s.a.'
 'asefa dukamo keroma' 'selian coffee estate' 'olam agro colombia'
 'chris finch' 'itochu corporation' 'owen carver'
 'pt.royal pacific indah international' 'andres martinez leon'
 'amanda powers' 'ipanema coffees' 'doi tung development project'
 'cafes tomari sa de cv' 'sarawut premjit' 'almacafe'
 'oscar ortega carballo' 'yasmin cofffee plantation plc' 'garet alban'
 'filemon mendoza campos' 'doi chaang coffee company' 'kennedy macharia'
 'nile highland arabica coffee farmers' 'german negron'
 'saul m. hernandez ramirez' 'comercial internacional exportadora, s.a.'
 'rob stephen' 'juan luis ortega carballo'
 'ekai international company ltd.' 'andreas kussmaul'
 'bulamburi coffee farmers association' 'damari absalome'
 'debesa agro industry plc' 'miguel cortes moreno'
 'gabriel bernardo rivas ross' 'felipe isaza'
 'specialty coffee association of indonesia' 'bugisu cooperative union'
 'bourbon specialty coffees' 'ngila estate ltd' 'j.andrade'
 'itiah coffee llc' 'cafe de don balbino s.c. de r.l. de c.v.'
 'productos y servicios chilindron s.a. de c.v.' 'calixto guillen vazquez'
 'ernesto rodriguez luna' 'modesto landeros flores' 'andrea bernal'
 'sunvirtue co., ltd.' 'tutunze kahawa ltd' 'cafe politico'
 'mayra yessenia torres' 'balam hinyula' 'nestor mendez gomez'
 'fernando mendoza aparicio' 'maria luisa del carmen rojas narvaez' 'ucfa'
 'irene alves santos' 'star cafe ltd' 'rosa aurora falcon fernandez'
 'santiago solis ayerdi' 'renee a. perrine' 'zarah zamora perez'
 'andrew bowman' 'expocaccer coop dos cafeic do cerrado ltda'
 'nyapea coffee farmers association' 'maria guadalupe gomez anzo'
 'royal base corporation' 'veronica lopez castillejos' 'samuel muhirwa'
 'joshua marsceau' 'coffeebythebag.com , inc' 'edwin agasso'
 'armando luis pohlenz martinez' 'coffee export'
 'sergio de la vequia bernardi' 'romulo bello flores' 'rachel peterson'
 'josé luis rojas yeo' 'nitin coffee estate' 'adam kline' 'montegrande'
 'grupo cafetalero los brujos spr de rl' 'george a. fernandez'
 'gabriel barbara' 'andry simarmata' 'brent hall'
 'guillermo rojas saldana' 'elsy reyes' 'shah plantations'
 'amkeni gourmet coffee group' 'enrique mitre lopez'
 'enrique eduardo lopez aguilar' 'brian beck' 'gladness obed pallangyo'
 'dario cesar galeana sanchez' 'jose daniel cobilt castro'
 'alvaro quiros perez' 'olivia hernandez virves' 'finca las nieves'
 'pedro santos e silva' 'michael gavina' 'klem organics'
 'jesus carlos cardenas valdivia' 'bencafe, s. a.' 'langiro farm group'
 'ibero coffee trading co (t) ltd' 'salvador caro carrion'
 'cafetalera internacional cafinter, s.a.' 'ngorogoro convenant estate'
 'julio perez hernandez' 'didas' 'minwook ku' 'finca estate'
 'beneficio santa rosa' 'jorge octavio escamilla prado' 'mcomafa co ltd'
 'juan hermilio sampieri carcamo' 'u mg mg' 'viridiana' 'kurt kappeli'
 'christina dusing' 'jorge francisco martinez hachity'
 'sergio landa alarcon' 'diego manuel woolrich ramirez' 'dae ltd company'
 'fredy gordillo reyes' 'virginia gordillo gordillo'
 'jose luis munoz guerrero' 'mdh' 'acacia hills ltd'
 'exportadora atlantic, s.a.' 'genius coffee'
 'santa laura exportadora de cafe s.l.e.c. s.a.' 'myriam kaplan-pasternak'
 'tomas edelmann blass' 'maria de la paz aguilar guillen'
 'angel oscar medina rodriguez' 'victoria' 'hector gabriel barreda nader'
 'shangrilla estate ltd' 'immaculata john' 'kerchanshe' 'gregorio sebba'
 'rolando lacayo' 'wali ali' 'obed rendon ponce'
 'gerardo hernandez valderrabano' 'balbino ramirez flores'
 'mlimani ngarashi' 'alejandro garcia palacios' 'grupo santab s.a de c.v.'
 'min hlaing' 'karatu estate' 'eduardo luis augusto velazquez solis'
 'luis roberto fermoso beltran' 'jose manuel vergara cortes' 'u soe'
 'burka coffee estate' 'janny marlith torres' 'case noyale ltd'
 'shwe yin mar coffee' 'israel eduardo paz garcia' 'adam ciruli ye'
 'delfina leon shine' 'kongoni estate' 'volcafe ltda. - brasil'
 'bob mccauley' 'u htun htun' 'gloria antonieta escobar urrutia'
 'honor dela fuente' 'pablo enrique martinez gama'
 'marco virgilio ramirez teliz' 'brayan cunha souza'
 'federico pacheco perez' 'ngu shwe li' 'semiramis casas velazquez'
 'jesus carlos cadena valdivia' 'asociación aldea global jinotega'
 'leonides de la cruz lopez' 'mario jose fernandez'
 'adriana torres rico quevedo' 'rre kunene' 'eric jesus cordoba arroyo'
 'julio cesar robles flores' 'masamichi hiroike'
 'juana rodriguez gutierrez' 'cafes finos de exportacion s de r.l.'
 'sustainable harvest coffee' 'gonzalo de aquino flores'
 'juan avenamar rodriguez funez' 'octavio augusto diaz trejo'
 'damaso martinez perez'
 'productores de especialidad emiliano zapeata, spr.'
 'juan garcia hernandez' 'rosario miguel hernandez' 'francisco ruiz nunez'
 'pablo cervantes morelos        ' 'gustavo amieva gonzalez'
 'samuel eli gurel' 'mao-heng chu' 'gustavo abarca solis'
 'stephany escamilla femat' 'homero antonio de anda andrade' 'william ho'
 'guillermo eduardo bobadilla muguira' 'ana gonzales'
 'francisco hernandez lorenzo' 'martin jimenez casiano'
 'grupo juvenil magtayani, ac' 'myrna roxana galvez gonzalez'
 'eugene holman pew' 'jose armando norberto borzani lemini'
 'ricardo aaron sampieri marini' 'juan carlos garcia lopez'
 'ankole coffee producers coop' 'nishant gurjer' 'andrew hetzel' 'ugacof'
 'katuka development trust ltd' 'kasozi coffee farmers association'
 'nitubaasa ltd' 'mannya coffee project' 'luis robles' 'james moore']

Country.of.Origin unique values:
['Ethiopia' 'Guatemala' 'Brazil' 'Peru' 'United States'
 'United States (Hawaii)' 'Indonesia' 'China' 'Costa Rica' 'Mexico'
 'Uganda' 'Honduras' 'Taiwan' 'Nicaragua' 'Tanzania, United Republic Of'
 'Kenya' 'Thailand' 'Colombia' 'Panama' 'Papua New Guinea' 'El Salvador'
 'Japan' 'Ecuador' 'United States (Puerto Rico)' 'Haiti' 'Burundi'
 'Vietnam' 'Philippines' 'Rwanda' 'Malawi' 'Laos' 'Zambia' 'Myanmar'
 'Mauritius' 'Cote d?Ivoire' 'India']

Farm.Name unique values:
['metad plc' 'san marcos barrancas "san cristobal cuch'
 'yidnekachew dabessa coffee plantation' 'aolme' 'tulla coffee farm'
 'fahem coffee plantation' 'el filo' 'los cedros' 'arianna farms'
 'el águila' 'toarco jaya' 'echo coffee' 'drima zede' 'el rodeo' 'several'
 'la herradura' 'la curva' 'fazenda kaquend' 'chebonet (23) women coffee'
 'los hicaques' 'tsoustructive garden 鄒築園' 'fazenda recreio'
 'exclusive coffees s.a.' 'haider abamecha coffee plantation' 'kangunu'
 'kona pacific farmers cooperative'
 'phone number | 0911-51-08-01, email | at' 'la primavera' 'co-op #12'
 'pereira estate coffee' 'sunshine valley estate 向陽高山咖啡' 'jungle estate'
 'kaasayi' 'ecobio colombia' 'kianjavi' 'contact | sidacoop@ethionet.net'
 'hula daddy kona coffee' 'la esperanza y anexos'
 'sipi organic coffee project' 'la berlina estate' 'valparaiso'
 'finca el limon' 'seid damtew coffee planation' 'tairora cherry – bonta'
 'el majahual' 'finca la esmeralda' 'elida estate' 'inoi' 'buginyanya'
 'asoperc' 'chesiyo farmer group' 'fazenda serra de três barras'
 'sierra nevada' "pu'er city longke coffee co.ltd" 'el injerto s.a.'
 'phone number | 0911-513824 email: gmt.ft' 'various'
 'coop. hoja blanca - fedecocagua' 'aricha coop' 'mount elgon area'
 'estate la patricia' 'machure estate' 'sitío são geraldo' 'kassandra'
 'la igualdad' 'baishengcun coffee 百勝村咖啡莊園' 'hasambo amcos' 'el suspiro'
 'fazenda grota funda' 'sitio claro' 'shi fang yuan 十方源'
 'mt.elgon bugisu shamba 2' 'matsuzawa coffee' 'karatina' 'cerro bueno'
 'santa martha' 'monterrey' 'sran temanggung plantation' 'ada farm'
 'rio jorco' 'san diego buena vista' 'coopetarrazú' 'moplaco'
 'finca salaca las brisas' 'dragon 龍咖啡' 'agropecuaria quiagral'
 'el nogal, la higuera, los laureles' 'blend' 'el morito' 'el papaturro'
 'la chaparral' 'fazenda vista alegre' 'kawacom sipi project'
 'menglian ban’an coffee processing factory'
 'puer jiangcheng fuwang coffee biotechnology co., ltd' 'el sacramento'
 'rumukia farmers' 'la barranca' 'finca el retiro' 'nueva granada'
 'several farmers' 'darmawi' 'tropica galliard' 'finca la chiripa'
 'kigwandi' 'las cuchillas' 'la distancia' 'santa alina'
 'fazenda baipendi' 'las minas' '馨晴咖啡 good mood coffee' 'finca medina'
 'finca san vicente' 'menglian county nayun town mangzhang coffee farm'
 'jacksom mwasenga' 'suma jkt itende' 'pante carajillo'
 'finca los barreales' 'finca santa teresa' 'piamonte' 'los girasoles'
 'finca la joya' 'santo tomas pachuj' 'chapultepec' 'las nubes' 'pantano'
 'gamboa' 'asefa dukamo coffee plantation' 'selian coffee estate'
 'café do paraíso' 'la union monte verde' 'el limon' 'mus, eman'
 'chang yu liang 張玉良' 'aprocafi' 'la lagunilla' 'kerchanshe'
 'finca los cerros y anexos' 'fazenda rio verde'
 'doi tung development project' '-' 'fazenda capoeirnha' 'cafetal'
 'saveg coffee farm' 'capoeirinha' 'very famous intl.名門義理國際股份有限公司' '神谷山莊園'
 'finca cuetzalingo' 'finca sant rosa' 'comunidad la yerbabuena'
 '優遊吧斯股份有限公司yuyupas international corp.' 'rio verde'
 '鄉舍咖啡 hometown coffee' 'finca el trueno' 'finca el morito'
 'predio cañada del encino' 'fazenda do sertao'
 'doi chaang coffee original co.,ltd' '崁頭山咖啡館 (kan tou mountain coffee)'
 'pu’er specialty coffee cupping center' 'erussi farmers group'
 'hacienda caracolillo' 'naranjal' 'several farms' 'santa matilde'
 'finca las cuevitas' 'finca quequesquez' 'finca apoxtla'
 'ijen highland, east java' 'finca santa clara'
 'menglian mang pan professional cooperative'
 'exportadora café california' 'lomi tasha' 'bulamburi coffee farmers'
 'dragon coffee 龍咖啡' 'ojo de agua' 'fazenda jericó' '南投縣魚池鄉水社村中正路63-1號'
 'la esperanza' 'ano family' 'yusrin' 'finca los barreales 1112lban'
 'la corralera' 'conquista / morito' 'pancoer angkrek' '日月潭文武莊園'
 'bulago & buginyanya' 'la joya' 'cachoeira da grama farm' 'ngila estate'
 'ecc' 'mondul coffee estate' 'el pino' 'marre blanche' 'sogestal kayanza'
 'corta pico' 'coopellanobonito' 'linda vista'
 'kawacom uganda ltd sipi farmers group' 'los charcos' '以勒咖啡'
 'finca teocelo' 'mata larga' 'água limpa' 'beneficio el torreon'
 'mamsera' 'apollo estate' 'bethel' 'chen lin'
 'yunnan success trade co.ltd' 'agua caliente'
 'la esperanza, margarita nuyes' 'myanganyanga' 'kaptanya' 'unkown'
 'el cerron' 'santa cecilia' 'tlapacoya' 'la loma' 'el mirador'
 'finca nueva linda' 'campo das flores' 'são francisco da serra'
 'fazenda do lobo' "olhos d'agua" 'tega and tula special coffee farm'
 'kan tou mountain coffee 崁頭山咖啡館' 'alishan zou zhu yuan 阿里山鄒築園'
 'santa maria' 'lintong nihuta' 'isule farmers group'
 'ibanda farmers group' 'el chile' 'fazenda santo antonio' '雅慕伊'
 'kabeywa county' 'grupo medina (pequeños productores)' 'sertao farm'
 'vegas' 'finca la estancia' 'las lomas' 'santa rosa' 'santa josefita'
 '佐佑品咖啡莊園' 'kalugmanan agri development corp.'
 'several, bukidnon, mindanao, philippines' 'pinzoneno'
 'fiech (mixed producers)' 'fazenda pantano' 'nyapea coffee farmers'
 'el regalito' 'apollo co., ltd.' 'el jabali' 'el barbaro' 'gicumbi'
 'santa fé 2' 'kampung keling, jumaraj, gurusinga, gongsol'
 'burka coffee estate' 'providencia' 'las merceditas' 'las delicias'
 'la esmeralda' '大鋤花間 (hoe vs. flower coffee farm)' 'la montaña'
 'man ganna estate' "pu'er lingdu yunlin coffee co.ltd" 'msese'
 'san lorenzo' 'tlamatoca' 'supply chain ecom cca s.a.'
 'hacienda la esmeralda' 'savan coffee bean' 'gabriel bernard rivas ross'
 'nitin' 'ampcg' '伊娜咖啡莊園' 'los llanitos' 'bugisu shamba'
 'zhuo wu shan coffee 卓武山咖啡農場' 'm10' 'finca monte grande'
 'finca castillos' 'la canada' '林園咖啡 lin yuan coffee' '台中市新社區崑山里'
 'small holders farmer' 'lubanda amcos' 'mt.elgon sipi falls cheema'
 'jamaica' 'la timbuchera; el ocotito y la hortaliza' 'fazenda chamusca'
 'shah plantation' 'amkeni' 'finca san el retiro' 'la pagua' 'caltuchoco'
 'santa cruz - pante don manuel' 'carrillo cooperativa'
 'menglian gao sanlin coffee factory' 'nguruma' 'fazenda serra negra'
 'cipresal' 'pante san pedro' 'cafetal el equimite, rancho agroecológico'
 'los barreales 1112lbcat_s110312' 'corral del diablo lote 1'
 'cañada fria' 'finca nextlalpa' 'fln mirador' 'santa mariana'
 'fazenda são pedro' 'yun lan coffee co. ltd' 'finca loma linda y anexo'
 'utchisi mountain' 'guo cun nong yuan 國村農園' 'yu jin gui 玉金櫃咖啡'
 'santa teresa' 'tepemalacax' 'finca los barreales 1112lbga7250412'
 'sitío santa luzia' 'cafetal santa maria' 'café citrus'
 'fazendas klem ltda' '眉泉莊園        ' 'zapato de mico' 'kachere'
 'guo xing ka fei wang 國姓咖啡王咖啡莊園' 'finca huehuetecpan' 'omicuatla'
 'los barreales 1112lbgr7230412' 'chilcuatla' 'comunidad de canoas'
 'caxambu' 'el brigadum - la coronela' 'langiro farm group' 'blue lake'
 'ilomba 2' 'song yue coffee 嵩岳咖啡' 'el nanchi' 'las truchas'
 'la calera, barranca de la leona, el nogal' 'el patalillo'
 'ngorogoro convenant estate' 'cafetalera aquiares' 'bola de oro'
 'tomatlancillo' 'las moras' 'family farm' 'club green' 'finca estate'
 'chikali' 'you siang coffee farmtainan, taiwan 台灣台南優香咖啡' 'bsr'
 'gao chun fang 高醇坊' 'la ceiba' 'são josé da lagoa' 'el faro'
 'santa mariana/são vicente' 'santa bárbara' 'las cebollas y anexos'
 'mcomafa farm no1155gr' 'mubuyu munali' 'platanal' 'texpanco' 'la laja'
 'sitío corrego da olaria/são caetano' 'helena' 'mudar' 'wat-ka-bu'
 'rancho bonito' 'dozen small farmer' 'kakoma'
 'gran manzana y el aguacate' 'finca muxbal' 'el deseo' 'cianorte'
 'los magueyes' 'finca tepictla'
 'arroyo triste, arroyo triste, san jose vista hermosa'
 'santa cruz - pante doña graciela' 'ngima' 'multiple' 'ilomba 1'
 'mu he zi coffee 木盒子咖啡園' 'guo xin ka fei 國昕咖啡' 'union ramal santa cruz'
 'finca cafetalera la suiza' 'ucipa santa catarina' 'sacún palma'
 'acacia hills' 'kavuzi' "jacob's estate 雅谷咖啡"
 'las nubes - pante don jaime' 'santa cruz - pante don jaime'
 'finca las marías' '谷泉咖啡莊園' 'mixed' 'chinongo'
 'good mood coffee 馨晴咖啡        ' 'xu yuan zhang 徐源漳' 'nueva linda'
 'productor independiente guadalupe victoria' 'santa maria temaxcalapa'
 'canoa manzanillo' 'hamburgo 7 arroyos' 'el romance azul' 'sertao'
 'chiquimulja / alpha cafe / senfro' 'fazenda rio brilhante' '山彎有機咖啡農場'
 'chimpumba' 'palantla' 'los brujos' 'fazenda sacramento' 'bacofa'
 'usingini farm' 'cruz verde' 'jing jing café 晶晶坊青山咖啡教室'
 'cafetales santa matilde' 'shangrilla estate' 'jia jia coffee 佳佳咖啡莊'
 'finca chanjul' 'las promesas de san blass' 'mviwambi coffee farmers'
 'irisan, baguio' 'makoka valley estate' 'juliana' 'fazenda são sebastião'
 'fazenda são josé mirante' 'mwalyego amcos' 'santa laura'
 'san fernando, chiapas' 'cafetal sinai' 'el desmoronado'
 'rural cooperative society' 'kapchorwa' 'taiwan hao ka 台灣好咖莊園'
 'finca el gavilancillo' '八杞莊園' 'thiririka/maara' 'finca monte azúl'
 'sithar coffee farm' 'karatu estate' '張文進莊園' 'bi yun si shi yi 碧云四十一咖啡坊'
 'bai he lin coffee 白鶴林咖啡莊園' 'heng lu coffee 橫鹿咖啡'
 'olotlan, el plan, criollo garnica' 'la victoria pante nubes'
 'selva negra' 'castelhana farm' 'myaing' 'juan damaso'
 'san josé y el portillo' '2000 farms' '胖胖糖'
 'el desmoronado, talpan de allende jalisco' 'leticia farm'
 'los saltarines' 'burka coffee estates' 'finca el naranjal' '王秋金'
 'el guayabo' 'la bendicion' 'case noyale ltd' 'barranca de las flores'
 'peña negra' '春風咖啡' 'finca la fany' "alicia's farm"
 'guoxing farm coffee 國姓農場咖啡        ' 'copalita' 'delfina farm'
 'kongoni estate' 'tokoffee莊園' 'la castellana'
 'são rafael_ ra/ras certified' 'cortapico' 'waylead farms' 'thein kone'
 'finca el consuelo' 'weng hui ling 翁惠鈴' 'mirador' 'los mesones'
 'la orduña, coatepec, veracruz' 'el carrizo' 'el aguacate' '好自在咖啡莊園'
 'sheng he shang pin coffee 聖荷上品咖啡坊' 'a shu she coffee 阿束社咖啡莊園'
 'wu kun shan coffee 吳焜山咖啡園' 'el tabaco' 'doe kwin'
 'zhang li hong coffee 張立宏咖啡莊園' 'santa clara, california y camila'
 'finca buenos aires' 'rancho san francisco iii' 'finca la orduña'
 'yara estate / benvar estate' 'asociación aldea global jinotega'
 'la cuchilla' 'ka-vulungan coffee estate' 'baijiada coffee farm佰加達咖啡莊園'
 'comonyaj noptic s de ss' 'el vergel' 'genuine antigua medina'
 'el encinal' 'consolapa' 'tepetzingo' 'su-zhen huang 黃素真' 'casa blanca'
 'cre-leg l-4' 'cnra station of divo' 'el encanto' 'la gloria'
 'baishencun coffee farm百勝村咖啡莊園' 'la tejeria' 'el delirio' 'huanacaxtle'
 'las palmas' 'el sauce' 'pico del oro' 'la pandora'
 'la patrona, el trebol, la cadena' 'el tesoro' 'los encinos' 'los pinos'
 'grapos el porvenir' 'cofradia' 'kona farms' 'finca sego'
 'cerca de los angeles' 'el naranjo' 'llano hermoso' 'hani'
 'finca la fortuna' 'el regadito'
 'dongshan gaoyuan village chief manor coffee tainan, taiwan 台灣台南東山高原村長莊園咖啡'
 'rancho los laureles' 'finca los andes'
 'producer group (approx. 1,000 farmers)' 'agua de la mariposa' '1'
 'zaragoza, montelibano, pamal navil' 'peña campana' 'la cruz' 'el limón'
 'la orduña' 'sierra madre' 'las ceibas' 'la marina-el orizabeño'
 'rancho vigia' '2000 farmers' 'la vuelta' 'la morena' 'el centenario'
 '200 farms' 'kyangundu cooperative society'
 'sethuraman estate kaapi royale' 'sethuraman estate'
 'ugacof project area' 'katikamu capca farmers association'
 'sethuraman estates' 'ishaka' 'kasozi coffee farmers'
 'kyangundu coop society' 'bushenyi' 'kigezi coffee farmers association'
 'mannya coffee project' 'robustasa' 'fazenda cazengo']

Lot.Number unique values:
['YNC-06114' '102' 'Tsoustructive 2015 Sumatra Typica' '11/23/0252'
 'Baby Geisha Washed' '320' 'YNC-16115' '11/23/0177' '6133' '3-37-1829'
 'LP-C211-180' 'Mezcla Veracruz 01' 'CN 11462 AA' '3-37-0277'
 '2016 Tainan Coffee Cupping Event Micro Lot 臺南市咖啡評鑑批次' 'MCTFHMG15/16'
 'Jan-71' '1' 'MCRKPBG 15/16' 'Tarrazu' '11/08/0109' '10NG0093'
 '3-37-1724' '3-37-1291' 'S015.367'
 '035/170/5071146\u2060\u2060\u2060\u2060' 'YNC-16018' '5-0015-0231'
 'MANDHELING BRASTAGI' '3-59-0318' 'K25159' '152' '76' '3-37-1704'
 '2017南投咖啡評鑑 NANTOU COFFEE EVALUATION EVENT 2017' 'MCCRNX115/16'
 '3-59-3461' '11/11711/59' '11/52/709' 'YNC-16017' '11/23/0365'

Several text fields contain inconsistent casing, spacing, and potential spelling variants. Some entries include non-English characters or long compound names. These will need normalization, typo correction, and possible grouping or exclusion during the cleaning phase.

#### Encoding and Character Issues

In [13]:
df_cqi['Certification.Contact'].sample(10)

88     19fef5a731de2db57d16da10287413f5f99bc2dd
895    7f521ca403540f81ec99daec7da19c2788393880
236    0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660
29     0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660
168    724f04ad10ed31dbb9d260f0dfd221ba48be8a95
17     61bbaf6a9f341e5782b8e7bd3ebf76aac89fe24b
702    aa2ff513ffb9c844462a1fb07c599bce7f3bb53d
803    5eb2b7129d9714c43825e44dc3bca9423de209e9
196    f6d87a6c04653c569d4911a66f89d5e30ce83b93
553    0eb4ee5b3f47b20b049548a2fd1e7d4a2b70d0a7
Name: Certification.Contact, dtype: object

This column, certification.contact will be dropped.

#### Unique Value Scan

In [14]:
# Count unique values in all object-type columns
df_cqi.select_dtypes(include='object').nunique().sort_values(ascending=False)

ICO.Number               845
Producer                 692
Farm.Name                571
Grading.Date             567
Expiration               566
Mill                     459
ICO.Number.1             396
Region                   356
Owner.1                  319
Owner                    315
Company                  281
Lot.Number               227
Bag.Weight                56
Harvest.Year              46
Country.of.Origin         36
Certification.Address     32
Variety                   29
Certification.Contact     29
In.Country.Partner        27
Certification.Body        26
Processing.Method          5
Color                      3
Species                    2
unit_of_measurement        2
dtype: int64

Some fields have too many unique values for grouping; others show clean, low-cardinality categories ideal for analysis.

#### Input Normalization

In [37]:
# Checking for inconsistencies
# 1. origin_country
print("origin_country:")
print(df_cqi['origin_country'].value_counts(dropna=False).sort_index(), end="\n\n")

origin_country:
origin_country
brazil                          132
burundi                           2
china                            16
colombia                        183
costa rica                       51
cote d?ivoire                     1
ecuador                           3
el salvador                      21
ethiopia                         44
guatemala                       181
haiti                             6
honduras                         53
india                            14
indonesia                        20
japan                             1
kenya                            25
laos                              3
malawi                           11
mauritius                         1
mexico                          236
myanmar                           8
nicaragua                        26
panama                            4
papua new guinea                  1
peru                             10
philippines                       5
rwanda                            1
taiwan                           75
tanzania, united republic of     40
thailand                         32
uganda                           36
united states                    10
united states (hawaii)           73
united states (puerto rico)       4
vietnam                           8
zambia                            1
NaN                               1
Name: count, dtype: int64

origin_country note:
Mostly clean and lowercase.
Fix encoding in "cote d?ivoire" to "côte d'ivoire".
Simplify "tanzania, united republic of" to "tanzania".
Collapse "united states (hawaii)" to "united states".
Treat "puerto rico" separately from "united states" if needed.

In [34]:
# Checking for inconsistencies
# 2. region
print("region:")
print(df_cqi['region'].value_counts(dropna=False).sort_index(), end="\n\n")

region:
region
52 narino (exact location: mattituy; municipal region: florida code 381     1
acatenango                                                                  3
aceh                                                                        1
aceh gayo                                                                   1
aceh tengah                                                                 1
                                                                           ..
嘉義阿里山                                                                       2
國姓鄉 guoshing township                                                       2
苗栗三灣                                                                        1
苗栗泰安                                                                        1
NaN                                                                        59
Name: count, Length: 357, dtype: int64

region note:
Highly fragmented—357 distinct values with many rare entries.
Contains detailed location strings, multilingual entries, and inconsistent formatting.
No normalization recommended without a reference table or geographic hierarchy.

In [35]:
# Checking for inconsistencies
# 3. variety
print("variety:")
print(df_cqi['variety'].value_counts(dropna=False).sort_index(), end="\n\n")

variety:
variety
arusha                     6
blue mountain              2
bourbon                  226
catimor                   20
catuai                    74
caturra                  256
ethiopian heirlooms        1
ethiopian yirgacheffe      2
gesha                     12
hawaiian kona             44
java                       2
mandheling                 3
marigojipe                 1
moka peaberry              1
mundo novo                33
other                    110
pacamara                   8
pacas                     13
pache comun                1
peaberry                   5
ruiru 11                   2
sl14                      17
sl28                      15
sl34                       8
sulawesi                   1
sumatra                    3
sumatra lintong            1
typica                   211
yellow bourbon            35
NaN                      226
Name: count, dtype: int64

variety note:
Mostly clean and domain-consistent.
No clear typos or casing issues.
“other” is broad—consider flagging for manual review.
Rare entries like “marigojipe” and “sumatra lintong” are valid but may benefit from grouping if analysis requires simplification.
No normalization needed unless varietal grouping is part of your analysis plan.

In [36]:
# Checking for inconsistencies
# 4. species
print("species:")
print(df_cqi['species'].value_counts(dropna=False).sort_index())

species:
species
arabica    1311
robusta      28
Name: count, dtype: int64

species note:
Clean and consistent.
Only includes “arabica” and “robusta” with no typos or formatting issues.
No normalization needed.

### 5. Column Status: Keep, Drop, or Review

#### Keep

In [15]:
columns_to_keep = [
    'Species',
    'Country.of.Origin',
    'Harvest.Year',
    'Processing.Method',
    'Color',
    'unit_of_measurement',
    'In.Country.Partner',
    'Certification.Body',
    'Variety',
    'Number.of.Bags',
    'Bag.Weight',
    'Aroma',
    'Flavor',
    'Aftertaste',
    'Acidity',
    'Body',
    'Balance',
    'Uniformity',
    'Clean.Cup',
    'Sweetness',
    'Cupper.Points',
    'Total.Cup.Points',
    'altitude_mean_meters',
    'Region',
    'Moisture',
    ]

These are clean, interpretable, and aligned with my analysis goals. They support origin context, production methods, and filtering logic. Low cardinality, clear semantics, and strong potential for enrichment—these are staying in.

#### Drop

In [16]:
columns_to_drop = [
    'ICO.Number',
    'Certification.Contact',
    'Certification.Address',
    'Producer',
    'Farm.Name',
    'Mill',
    'Company',
    'Lot.Number',
    'Grading.Date',
    'Expiration',
    'Owner.1',
    'Category.One.Defects',
    'Category.Two.Defects'
]

These fields are being dropped due to high cardinality, unclear context, or lack of analytical value. Most are unique identifiers, fragmented text, or fields without interpretable meaning. They don’t support grouping, enrichment, or storytelling, so they’re out.

#### Review

In [17]:
columns_to_review = [
    'Owner',
    'Region',
    'Moisture',
    'Quakers',
    'altitude_low_meters',
    'altitude_high_meters'
]

These are on the fence. Some might be salvageable with normalization or clarification, while others need unit context or grading logic. I’m holding off on decisions here until I’ve looked into this more.

## Data Cleaning
### Table of Contents
1. Dropping Columns
2. Standardize Headers and Text Fields
3. Normalize Inputs (needed????)
4. Missing Values
5. Export

### 1. Dropping Columns

After reviewing all the columns, I have decided on the following columns to be dropped.

In [18]:
columns_to_drop = [
    "Unnamed_Index'",
    'Farm.Name',
    'Lot.Number',
    'Mill',
    'ICO.Number',
    'Company',
    'ICO.Number.1',
    'Producer',
    'Number.of.Bags',
    'Bag.Weight',
    'Grading.Date',
    'Owner.1',
    'Category.One.Defects',
    'Quakers',
    'Color',
    'Category.Two.Defects',
    'Expiration',
    'Certification.Body',
    'Certification.Address',
    'Certification.Contact',
    'altitude_low_meters',
    'altitude_high_meters'
]

df_cqi = df_cqi.drop(columns=columns_to_drop)

In [19]:
# Work Check
df_cqi.columns.tolist()

['Species',
 'Owner',
 'Country.of.Origin',
 'Region',
 'In.Country.Partner',
 'Harvest.Year',
 'Variety',
 'Processing.Method',
 'Aroma',
 'Flavor',
 'Aftertaste',
 'Acidity',
 'Body',
 'Balance',
 'Uniformity',
 'Clean.Cup',
 'Sweetness',
 'Cupper.Points',
 'Total.Cup.Points',
 'Moisture',
 'unit_of_measurement',
 'altitude_mean_meters']

### 2. Standardize Headers and Text Fields

#### Headers

In [22]:
# Standardize Header Format
df_cqi.columns = (
    df_cqi.columns
    .str.strip()
    .str.lower()
    .str.replace('\n', ' ')
    .str.replace('\r', '')
    .str.replace('.', '_')
)

In [23]:
# Work check
df_cqi.columns.tolist()

['species',
 'owner',
 'country_of_origin',
 'region',
 'in_country_partner',
 'harvest_year',
 'variety',
 'processing_method',
 'aroma',
 'flavor',
 'aftertaste',
 'acidity',
 'body',
 'balance',
 'uniformity',
 'clean_cup',
 'sweetness',
 'cupper_points',
 'total_cup_points',
 'moisture',
 'unit_of_measurement',
 'altitude_mean_meters']

In [24]:
# Rename headers to be consistant 
df_cqi.rename(columns={
    'country_of_origin': 'origin_country',
    'in_country_partner': 'local_partner'
}, inplace=True)

In [25]:
# Work check
df_cqi.columns.tolist()

['species',
 'owner',
 'origin_country',
 'region',
 'local_partner',
 'harvest_year',
 'variety',
 'processing_method',
 'aroma',
 'flavor',
 'aftertaste',
 'acidity',
 'body',
 'balance',
 'uniformity',
 'clean_cup',
 'sweetness',
 'cupper_points',
 'total_cup_points',
 'moisture',
 'unit_of_measurement',
 'altitude_mean_meters']

#### Standardize Text Field Values

In [27]:
# ID text columns
text_columns = df_cqi.select_dtypes(include='object').columns.tolist()

In [28]:
# Define Standardization Function
def standardize_text(text):
    if pd.isna(text):
        return text
    return (
        str(text)
        .strip()                     # Remove leading/trailing whitespace
        .lower()                     # Convert to lowercase
        .replace('\n', ' ')          # Remove line breaks
        .replace('\r', '')           # Remove carriage returns
    )

In [29]:
# Apply to text columns
df_cqi[text_columns] = df_cqi[text_columns].applymap(standardize_text)

C:\Users\Chase\AppData\Local\Temp\ipykernel_26032\3722561294.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_cqi[text_columns] = df_cqi[text_columns].applymap(standardize_text)

In [30]:
# Work check
df_cqi[['species', 'origin_country', 'processing_method']].sample(5)

      species origin_country processing_method
1214  arabica      nicaragua               NaN
167   arabica         mexico      washed / wet
1008  arabica         uganda     natural / dry
565   arabica      guatemala      washed / wet
551   arabica      guatemala      washed / wet

### 3. Normalize Inputs

In [38]:
# Adressing 1. origin_country
# Normalize origin_country values
origin_country_map = {
    "cote d?ivoire": "côte d'ivoire",
    "tanzania, united republic of": "tanzania",
    "united states (hawaii)": "united states",
    "united states (puerto rico)": "puerto rico"
}

df_cqi['origin_country'] = df_cqi['origin_country'].replace(origin_country_map)

In [40]:
# Work check
print(df_cqi['origin_country'].value_counts(dropna=False).sort_index())

origin_country
brazil              132
burundi               2
china                16
colombia            183
costa rica           51
côte d'ivoire         1
ecuador               3
el salvador          21
ethiopia             44
guatemala           181
haiti                 6
honduras             53
india                14
indonesia            20
japan                 1
kenya                25
laos                  3
malawi               11
mauritius             1
mexico              236
myanmar               8
nicaragua            26
panama                4
papua new guinea      1
peru                 10
philippines           5
puerto rico           4
rwanda                1
taiwan               75
tanzania             40
thailand             32
uganda               36
united states        83
vietnam               8
zambia                1
NaN                   1
Name: count, dtype: int64

### 4. Missing Values

In [42]:
# Create a summary table of missing values for CQI dataset, excluding 0s
missing_count = df_cqi.isnull().sum()
missing_percent = (df_cqi.isnull().mean() * 100).round(2)

missing_summary = pd.DataFrame({
    'Missing Count': missing_count,
    'Missing %': missing_percent
})

# Filter out rows with 0 missing values
missing_summary = missing_summary[missing_summary['Missing Count'] > 0]

# Sorted by highest missing %
missing_summary = missing_summary.sort_values(by='Missing %', ascending=False)

# Display the summary
missing_summary

                      Missing Count  Missing %
altitude_mean_meters            230      17.18
variety                         226      16.88
processing_method               170      12.70
region                           59       4.41
harvest_year                     47       3.51
owner                             7       0.52
origin_country                    1       0.07

Several columns contain missing values that cannot be reliably imputed. To preserve transparency and analytical integrity:
- Numeric columns (altitude_mean_meters, harvest_year) will remain as NaN to avoid introducing bias or distortion.
- String columns (variety, processing_method, owner) will be filled with "Unknown" to maintain categorical structure while signaling absence.
- This approach ensures the dataset remains unskewed, auditable, and ready for downstream analysis.
- I will investigate region and origin_country further to determine whether missing values can be inferred based on known patterns or relationships.

In [43]:
# Display row where origin_country is missing
missing_country_row = df_cqi[df_cqi['origin_country'].isna()]
print(missing_country_row)

      species               owner origin_country region local_partner  \
1197  arabica  racafe & cia s.c.a            NaN    NaN      almacafé

     harvest_year variety processing_method  aroma  flavor  ...  body  \
1197          NaN     NaN               NaN   6.75    6.75  ...  7.58

      balance  uniformity  clean_cup  sweetness  cupper_points  \
1197      7.5        10.0       10.0       10.0           7.25

      total_cup_points  moisture  unit_of_measurement  altitude_mean_meters
1197             79.08       0.1                    m                   NaN

[1 rows x 22 columns]

In [46]:
# Filter rows with same owner: racafe & cia s.c.a to see if one has a origin_country entry
racafe_rows = df_cqi[
    (df_cqi['owner'].str.lower() == 'racafe & cia s.c.a') &
    (df_cqi['origin_country'].notna())
]

# Display relevant columns
print(racafe_rows[['origin_country', 'region']])

     origin_country     region
97         colombia      huila
106        colombia      huila
107        colombia      huila
110        colombia      huila
145        colombia  santander
146        colombia      huila
151        colombia      huila
174        colombia      huila
183        colombia   la plata
197        colombia      huila
198        colombia      huila
211        colombia      huila
216        colombia      huila
235        colombia      huila
249        colombia      huila
268        colombia      huila
275        colombia      huila
299        colombia      huila
304        colombia      huila
325        colombia      huila
337        colombia      huila
339        colombia      huila
347        colombia      huila
356        colombia      huila
371        colombia      huila
397        colombia    guayata
398        colombia      huila
436        colombia   la plata
455        colombia      huila
467        colombia      huila
479        colombia      huila
492        colombia      huila
513        colombia      huila
517        colombia      huila
525        colombia   la plata
527        colombia      cauca
535        colombia    guayata
549        colombia      huila
557        colombia      cauca
571        colombia      huila
592        colombia      huila
603        colombia      huila
632        colombia        NaN
651        colombia      huila
671        colombia      huila
679        colombia    guayata
691        colombia      huila
753        colombia      huila
755        colombia      cauca
805        colombia      huila
814        colombia      huila
850        colombia      huila
869        colombia      huila
876        colombia   la plata
932        colombia      cauca
950        colombia      huila
1002       colombia    guayata
1059       colombia        NaN
1067       colombia        NaN

In [47]:
# From the above list it shows the company is out of Colombia. I will enter this data in
# Fill origin_country for the Racafé row
df_cqi.loc[df_cqi['owner'].str.lower() == 'racafe & cia s.c.a', 'origin_country'] = 'colombia'

In [49]:
# Work check
# Count missing values in origin_country
missing_origin_country = df_cqi['origin_country'].isna().sum()
print(f"Missing origin_country values: {missing_origin_country}")

Missing origin_country values: 0

In [50]:
# Display origin_country and region side by side to investigate regions
country_region_view = df_cqi[['origin_country', 'region']].sort_values(by=['origin_country', 'region'])
print(country_region_view)

     origin_country                     region
987          brazil  alta paulista (sao paulo)
734          brazil      brazil matas de minas
421          brazil     campos altos - cerrado
637          brazil     campos altos - cerrado
681          brazil     campos altos - cerrado
...             ...                        ...
860         vietnam                    vietnam
502         vietnam            vietnam cau dat
564         vietnam              vietnam tutra
1338        vietnam                        NaN
823          zambia              mubuyu estate

[1339 rows x 2 columns]

In [45]:
# Filter rows with missing region but known origin_country
missing_region_candidates = df_cqi[df_cqi['region'].isna() & df_cqi['origin_country'].notna()]
print(missing_region_candidates[['origin_country', 'region']])

     origin_country region
2         guatemala    NaN
5            brazil    NaN
6              peru    NaN
30        nicaragua    NaN
31         tanzania    NaN
100           kenya    NaN
114           kenya    NaN
134      costa rica    NaN
152           kenya    NaN
223       guatemala    NaN
240      costa rica    NaN
257        thailand    NaN
293        thailand    NaN
334   united states    NaN
352          taiwan    NaN
373   united states    NaN
379          taiwan    NaN
394        thailand    NaN
407            peru    NaN
415   united states    NaN
443            peru    NaN
457        colombia    NaN
495       guatemala    NaN
521        colombia    NaN
526        thailand    NaN
528   united states    NaN
529   united states    NaN
532        thailand    NaN
548       guatemala    NaN
558        thailand    NaN
623     el salvador    NaN
626          mexico    NaN
632        colombia    NaN
645       guatemala    NaN
690        honduras    NaN
735          taiwan    NaN
749     el salvador    NaN
754          brazil    NaN
784        colombia    NaN
822       nicaragua    NaN
824        honduras    NaN
862          brazil    NaN
908        thailand    NaN
997   united states    NaN
1029       thailand    NaN
1059       colombia    NaN
1066  united states    NaN
1067       colombia    NaN
1101       colombia    NaN
1116      nicaragua    NaN
1164       thailand    NaN
1215      nicaragua    NaN
1242       colombia    NaN
1247         brazil    NaN
1278         mexico    NaN
1295       colombia    NaN
1337          india    NaN
1338        vietnam    NaN

After reviewing the country–region pairs, I’ve determined that I cannot safely impute region based on origin_country. Many countries have multiple distinct regions or highly specific entries, and forcing a single match would risk skewing the analysis. To preserve transparency and analytical integrity, missing region values will be filled with - unknown.

In [53]:
# Define string columns to fill
string_cols = ['variety', 'processing_method', 'owner', 'region']

# Fill missing string values with "Unknown"
df_cqi[string_cols] = df_cqi[string_cols].fillna('unknown')

In [54]:
# Work check
# Show missing value counts for string columns
string_cols = ['variety', 'processing_method', 'owner', 'region']
print(df_cqi[string_cols].isna().sum())

variety              0
processing_method    0
owner                0
region               0
dtype: int64

Unknown imputation was successful

In [55]:
# Show missing value counts for numeric columns
numeric_cols = ['altitude_mean_meters', 'harvest_year']
print(df_cqi[numeric_cols].isna().sum())

altitude_mean_meters    230
harvest_year             47
dtype: int64

This is fine since I'm leaving as NaN

### 5. Export

In [57]:
# Export cleaned CQI dataset
df_cqi.to_csv(r"C:\Users\Chase\anaconda_projects\Exercise_6_Coffee\A6_Coffee\02_Data\Prepared_Data\Coffee_Quality_database_from_CQI\coffee_quality_cqi_clean.csv", index=False)