# Merging Datasets
1. Imports/Pathways
2. Data Inspection
3. Merge
4. Merge Inspection
5. Merge Corrections
6. Export

## 1. Imports/Pathways

In [11]:
# Import libraries
import pandas as pd
import numpy as np
import re

In [12]:
# File Pathway
path = r"C:\Users\Chase\anaconda_projects\Exercise_6_Coffee\A6_Coffee"

In [13]:
# Import Main dataset
df_top = pd.read_csv(
    r'C:\Users\Chase\anaconda_projects\Exercise_6_Coffee\A6_Coffee\02_Data\Prepared_Data\Top Rated Coffee\top_rated_coffee_wrangled.csv')

In [14]:
# Import 2nd dataset
df_cqi = pd.read_csv(
    r'C:\Users\Chase\anaconda_projects\Exercise_6_Coffee\A6_Coffee\02_Data\Prepared_Data\Coffee_Quality_database_from_CQI\coffee_quality_database_from_cqi_wrangled.csv')

## 2. Data Inspection

In [15]:
# Quick structure check
print(df_top.shape)
print(df_cqi.shape)

(2210, 15)
(1339, 22)

In [16]:
# Column overview
print(df_top.columns)
print(df_cqi.columns)

Index(['coffee_name', 'total_score', 'roast_level', 'agtron_roast',
       'price_usd', 'quantity_g', 'usd_per_gram', 'roaster_location',
       'roaster_city', 'roaster_region', 'roaster_country', 'coffee_origin',
       'coffee_city', 'coffee_region', 'coffee_country'],
      dtype='object')
Index(['species', 'owner', 'origin_country', 'region', 'local_partner',
       'harvest_year', 'variety', 'processing_method', 'aroma', 'flavor',
       'aftertaste', 'acidity', 'body', 'balance', 'uniformity', 'clean_cup',
       'sweetness', 'cupper_points', 'total_cup_points', 'moisture',
       'unit_of_measurement', 'altitude_mean_meters'],
      dtype='object')

In [17]:
# Sample rows
df_top.head(3)
df_cqi.head(3)

,species,owner,origin_country,region,local_partner,harvest_year,variety,processing_method,aroma,flavor,...,body,balance,uniformity,clean_cup,sweetness,cupper_points,total_cup_points,moisture,unit_of_measurement,altitude_mean_meters
0,arabica,metad plc,ethiopia,guji-hambela,metad agricultural development plc,2014.0,unknown,washed / wet,8.67,8.83,...,8.50,8.42,10.0,10.0,10.0,8.75,90.58,0.12,m,2075.0
1,arabica,metad plc,ethiopia,guji-hambela,metad agricultural development plc,2014.0,other,washed / wet,8.75,8.67,...,8.42,8.42,10.0,10.0,10.0,8.58,89.92,0.12,m,2075.0
2,arabica,grounds for health admin,guatemala,unknown,specialty coffee association,NaN,bourbon,unknown,8.42,8.50,...,8.33,8.42,10.0,10.0,10.0,9.25,89.75,0.00,m,1700.0

In [18]:
# Nulls and uniqueness
df_top.isnull().sum()
df_cqi.isnull().sum()

df_top.nunique().sort_values()
df_cqi.nunique().sort_values()

species                   2
unit_of_measurement       2
processing_method         6
harvest_year              9
uniformity               10
clean_cup                11
sweetness                17
moisture                 23
local_partner            26
variety                  30
acidity                  31
balance                  33
aroma                    33
body                     33
aftertaste               35
origin_country           35
flavor                   35
cupper_points            42
total_cup_points        180
altitude_mean_meters    211
owner                   316
region                  357
dtype: int64

It looks like I only have two Primary Keys to do a merge with, country and region based columns.

## 3. Merge

In [55]:
# First rename column headers to match to make the merge easier. coffee_country & coffee_region will be the headers.
df_cqi.rename(columns={'origin_country': 'coffee_country', 'region': 'coffee_region'}, inplace=True)

In [56]:
# Merge. Use left merge on the two PKs.
df_coffee_merged = pd.merge(df_top, df_cqi, on=['coffee_country', 'coffee_region'], how='left')

## 4. Merge Inspection

In [57]:
# Shape check
df_coffee_merged.shape

(8877, 35)

In [58]:
# Info check
df_coffee_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8877 entries, 0 to 8876
Data columns (total 35 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   coffee_name           8877 non-null   object
 1   total_score           8877 non-null   float64
 2   roast_level           8877 non-null   object
 3   agtron_roast          8877 non-null   object
 4   price_usd             8877 non-null   object
 5   quantity_g            8877 non-null   object
 6   usd_per_gram          8877 non-null   object
 7   roaster_location      8877 non-null   object
 8   roaster_city          8877 non-null   object
 9   roaster_region        8877 non-null   object
 10  roaster_country       8877 non-null   object
 11  coffee_origin         8877 non-null   object
 12  coffee_city           8877 non-null   object
 13  coffee_region         8877 non-null   object
 14  coffee_country        8877 non-null   object
 15  species               7342 non-null   object
 16  owner                 7342 non-null   object
 17  local_partner         7342 non-null   object
 18  harvest_year          5020 non-null   float64
 19  variety               7342 non-null   object
 20  processing_method     7342 non-null   object
 21  aroma                 7342 non-null   float64
 22  flavor                7342 non-null   float64
 23  aftertaste            7342 non-null   float64
 24  acidity               7342 non-null   float64
 25  body                  7342 non-null   float64
 26  balance               7342 non-null   float64
 27  uniformity            7342 non-null   float64
 28  clean_cup             7342 non-null   float64
 29  sweetness             7342 non-null   float64
 30  cupper_points         7342 non-null   float64
 31  total_cup_points      7342 non-null   float64
 32  moisture              7342 non-null   float64
 33  unit_of_measurement   7342 non-null   object
 34  altitude_mean_meters  4763 non-null   float64
dtypes: float64(15), object(20)
memory usage: 2.4+ MB

In [59]:
# Check rows
df_coffee_merged.head(3)

,coffee_name,total_score,roast_level,agtron_roast,price_usd,quantity_g,usd_per_gram,roaster_location,roaster_city,roaster_region,...,body,balance,uniformity,clean_cup,sweetness,cupper_points,total_cup_points,moisture,unit_of_measurement,altitude_mean_meters
0,colombia finca campo hermosa,94.0,light,82.0,29.99,226.8,$29.99 / 226.8g,"cleveland, tennessee",cleveland,tennessee,...,7.58,7.58,10.0,10.0,10.0,7.58,83.17,0.11,m,NaN
1,colombia finca campo hermosa,94.0,light,82.0,29.99,226.8,$29.99 / 226.8g,"cleveland, tennessee",cleveland,tennessee,...,7.75,7.50,10.0,10.0,10.0,7.50,83.00,0.00,m,NaN
2,colombia finca campo hermosa,94.0,light,82.0,29.99,226.8,$29.99 / 226.8g,"cleveland, tennessee",cleveland,tennessee,...,7.67,7.83,10.0,10.0,10.0,7.58,82.67,0.21,m,NaN

In [60]:
# Check the merge success rate and how many rows were enriched
df_coffee_merged['species'].notnull().mean()

np.float64(0.8270812211332658)

82.7% matched up

In [61]:
# Preview unmatched rows
df_coffee_merged[df_coffee_merged['species'].isnull()][['coffee_country', 'coffee_region']].value_counts().head(10)

coffee_country  coffee_region
unknown         unknown          776
united states   hawaii           133
indonesia       sumatra           56
ethiopia        guji              56
                unknown           46
panama          unknown           37
                panama            18
                volcan            14
indonesia       unknown           13
ethiopia        jimma             13
Name: count, dtype: int64

## 5. Merge Corrections

In [37]:
# Patch Known Regions with Missing Countries
region_country_patch = {
    'hawaii': 'united states',
    'oromia': 'ethiopia',
    'yirgacheffe': 'ethiopia',
    'gedeo': 'ethiopia',
    'guji': 'ethiopia',
    'sumatra': 'indonesia',
    'valle del cauca': 'colombia'
}

In [38]:
# Apply patch
df_top['coffee_country'] = df_top.apply(
    lambda row: region_country_patch.get(row['coffee_region'].lower(), row['coffee_country'])
    if row['coffee_country'].lower() == 'unknown' else row['coffee_country'],
    axis=1
)

In [39]:
# Work check
df_top[df_top['coffee_country'].isin(['unknown', 'united states', 'ethiopia', 'indonesia', 'colombia'])][['coffee_country', 'coffee_region']].drop_duplicates().head(10)

   coffee_country    coffee_region
0        colombia          unknown
3        ethiopia            kaffa
4         unknown          unknown
11       colombia  valle del cauca
12       colombia            cauca
14       ethiopia            gedeo
15       ethiopia           oromia
16        unknown        pichincha
21       colombia            huila
26  united states           hawaii

In [43]:
# Patch on region and country
region_country_patch = {
    'gedeo': 'guji',
    'guji': 'guji',
    'boquete': 'panama',
    'valle del cauca': 'cauca'  # or 'huila' depending on CQI listings
}

In [44]:
df_top['coffee_country'] = df_top.apply(
    lambda row: region_country_patch.get(row['coffee_region'].lower(), row['coffee_country'])
    if row['coffee_country'].lower() == 'unknown' else row['coffee_country'],
    axis=1
)

df_top['coffee_region'] = df_top['coffee_region'].replace(region_country_patch)

In [53]:
# patch region and country v2
region_country_patch.update({
    'volcan': 'panama',
    'panama': 'panama'  # for rows where country is blank
})

In [54]:
df_top['coffee_country'] = df_top.apply(
    lambda row: region_country_patch.get(row['coffee_region'].lower(), row['coffee_country'])
    if row['coffee_country'].lower() == 'unknown' else row['coffee_country'],
    axis=1
)

## 6. Export

In [62]:
# Export
df_coffee_merged.to_csv(
    r'C:\Users\Chase\anaconda_projects\Exercise_6_Coffee\A6_Coffee\02_Data\Prepared_Data\Coffee_Datasets_Merged.csv',
    index=False
)